import string
import random

letters = list(string.ascii_uppercase)
digits = list(string.digits)

all_chars = letters + digits

# Generating a Microsoft Windows 11 Pro product key
print("Format should be like this  XXXXX-XXXXX-XXXXX-XXXXX-XXXXX\n")

print("Welcome to Product Key Generator!\n")
print(
    "\nFirst method: We used join all the characters generated by generator expression into a single string.\nThis "
    "operation is highly efficient and avoids the overhead of repeated string concatenation.\n")
password = ''.join(random.choice(all_chars) + ('-' if i % 5 == 0 and i != 25 else '') for i in range(1, 26))
print(password)

print(
    "\nSecond method: We used for loops which manually appends characters to a string within the loop\nwhich involves "
    "more steps and can be less efficient due to repeated string concatenation operations.\n")
# Other way to generate
password_2 = ''
for i in range(1, 26):
    password_2 += random.choice(all_chars)
    if i % 5 == 0 and i != 25:
        password_2 += '-'
    else:
        password_2 += ''
print(password_2)
